name: Check wordpress-stubs

on:
  workflow_dispatch:

env:
  SOURCE_REPO_URL: https://github.com/php-stubs/wordpress-stubs.git
  SOURCE_FILE_PATH: wordpress-stubs.php
  TARGET_REPO_NAME: wordpress-stubs

jobs:

  check:
    runs-on: ubuntu-latest
    name: Check for Changes
    outputs:
      changes: ${{ steps.check.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
      - name: Install Dependencies
        run: composer install --no-interaction
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Check for Changes
        id: check
        run: echo "changes=$(./bin/find-changes --working-dir=./tmp $SOURCE_REPO_URL $SOURCE_FILE_PATH $TARGET_REPO_NAME)" >> "$GITHUB_OUTPUT"

  dispatch:
    runs-on: ubuntu-latest
    needs: check
    strategy:
      matrix:
        include: ${{ fromJson(needs.check.outputs.changes) }}
    name: Dispatch ${{ matrix.tag }}
    steps:
      - name: Testing
        run: echo "hello ${{ matrix.name }}"
      - name: Dispatch Update Event
        if: ${{ matrix.name == 'UPDATE' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: update-tag
          client-payload: '{"tag": "${{ matrix.tag }}"}'
