name: Check All

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Lastrun
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Committer Info
        run: |
          git config --global user.name "${{ vars.COMMITTER_NAME }}"
          git config --global user.email "${{ vars.COMMITTER_EMAIL }}"
      - name: Set Lastrun
        run: |
          DATE=$(date)
          echo $DATE >> .lastrun
          git add .lastrun
          git commit -m "Last Run: $DATE"
          git push

  dispatch:
    needs: update
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - source: https://github.com/php-stubs/wordpress-stubs.git
            path: wordpress-stubs.php
            target: wordpress-stubs
    name: Check Source (${{ matrix.target }})
    steps:
      - name: Dispatch Check Event
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: check-tags
          client-payload: '{"source": "${{ matrix.source }}", "path": "${{ matrix.path }}", "target": "${{ matrix.target }}"}'
