name: Create Tag

on:
  repository_dispatch:
    types: [create-tag]

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: 'echo "tag: ${{ github.event.client_payload.tag }}"'