name: Create Tag

on:
  repository_dispatch:
    types: [create-tag]

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "SOURCE: ${{ github.event.client_payload.source }}"'
      - run: 'echo "TAG: ${{ github.event.client_payload.tag }}"'
      - run: 'echo "PATH: ${{ github.event.client_payload.path }}"'
      - run: 'echo "TARGET: ${{ github.event.client_payload.target }}"'