name: Delete Tag

on:
  repository_dispatch:
    types: [delete-tag]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: 'echo "tag: ${{ github.event.client_payload.tag }}"'