name: Delete Tag

on:
  repository_dispatch:
    types: [delete-tag]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "TAG: ${{ github.event.client_payload.tag }}"'
      - run: 'echo "TARGET: ${{ github.event.client_payload.target }}"'