name: Update Tag

on:
  repository_dispatch:
    types: [update-tag]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "SOURCE: ${{ github.event.client_payload.source }}"'
      - run: 'echo "TAG: ${{ github.event.client_payload.tag }}"'
      - run: 'echo "PATH: ${{ github.event.client_payload.path }}"'
      - run: 'echo "TARGET: ${{ github.event.client_payload.target }}"'
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
      - name: Install Dependencies
        run: composer install --no-interaction
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Delete Tag
        run: ./bin/delete-version --working-dir=./delete ${{ github.event.client_payload.target }} ${{ github.event.client_payload.tag }}
      - name: Create Tag
        run: ./bin/create-version --working-dir=./create ${{ github.event.client_payload.source }} ${{ github.event.client_payload.tag }} ${{ github.event.client_payload.path }} ${{ github.event.client_payload.target }}