name: Update Tag

on:
  repository_dispatch:
    types: [update-tag]

jobs:
  update:
    name: Update Tag - ${{ github.event.client_payload.target }} ${{ github.event.client_payload.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
      - name: Install Dependencies
        run: composer install --no-interaction
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets[github.event.client_payload.key] }}
      - name: Set Committer Info
        run: |
          git config --global user.name "${{ vars.COMMITTER_NAME }}"
          git config --global user.email "${{ vars.COMMITTER_EMAIL }}"
      - name: Delete Tag
        run: ./bin/delete-version --working-dir=./delete ${{ github.event.client_payload.target }} ${{ github.event.client_payload.tag }}
      - name: Create Tag
        run: ./bin/create-version --working-dir=./create ${{ github.event.client_payload.source }} ${{ github.event.client_payload.tag }} ${{ github.event.client_payload.path }} ${{ github.event.client_payload.target }}